/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report dependency health
         * @description Report database reachability and the presence of the btree_gist extension.
         *
         *     Returns 200 when everything the application needs is present, and 503 when
         *     it is not, so an uptime check does not have to parse the body to decide
         *     whether the service is usable.
         */
        get: operations["read_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for an access token
         * @description Verify credentials and issue an access token.
         *
         *     Args:
         *         payload: The email address and password as typed.
         *         session: The request scoped database session.
         *
         *     Returns:
         *         The access token, its lifetime and the account it belongs to.
         *
         *     Raises:
         *         AuthenticationFailure: If no account matches or the password is wrong.
         *         InactiveAccount: If the credentials are right but the account is
         *             deactivated. Reported separately from a wrong password because the
         *             holder needs to know to contact an administrator.
         */
        post: operations["post_sign_in_api_auth_sign_in_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the signed in account
         * @description Return the account behind the presented access token.
         *
         *     Args:
         *         user: The active account, resolved by the layered auth dependencies.
         *         session: The request scoped session, used to resolve the branch code.
         *
         *     Returns:
         *         The account in the shape the frontend UserAccount type expects.
         */
        get: operations["read_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hold specific assets for a hire period
         * @description Create a held reservation and allocate specific assets to it.
         *
         *     Args:
         *         payload: The product model, branch, half open period and quantity.
         *         user: The active account making the request.
         *         use_case: The reservation use case. It owns the commit.
         *
         *     Returns:
         *         The committed reservation with the tagged units held.
         *
         *     Raises:
         *         ValidationFailure: If the period is not a valid hire period.
         *         AuthorisationFailure: If a customer tries to book on someone else's behalf.
         *         AllocationConflictError: If no free unit exists. Mapped to HTTP 409.
         */
        post: operations["post_allocation_api_allocations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the trading branches
         * @description Return every active branch, ordered by name.
         */
        get: operations["list_branches_api_branches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the catalogue categories
         * @description Return every active category, each parent followed by its children.
         *
         *     `modelCount` counts the published models of a category, and for a parent
         *     it includes the models of its children.
         */
        get: operations["list_categories_api_catalogue_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the published models
         * @description Return one page of the published models that match the query.
         *
         *     Raises:
         *         ValidationFailure: If the category is unknown. Mapped to HTTP 422.
         */
        get: operations["list_models_api_catalogue_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/models/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return one published model
         * @description Return the published model with this slug.
         *
         *     Raises:
         *         NotFound: If no published model carries the slug. Mapped to HTTP 404.
         */
        get: operations["read_model_api_catalogue_models__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search availability across the catalogue
         * @description Return one page of models with an answer from every active branch.
         *
         *     Raises:
         *         ValidationFailure: If the period, the category or the branch is
         *             refused. Mapped to HTTP 422, naming the parameter.
         */
        get: operations["search_availability_api_catalogue_availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogue/models/{slug}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return where one model is free
         * @description Return the branches where at least `quantity` units are free for the period.
         *
         *     Raises:
         *         NotFound: If no published model carries the slug. Mapped to HTTP 404.
         *         ValidationFailure: If the period or the quantity is refused, or the
         *             period is outside the hire limits of the model. Mapped to HTTP 422.
         */
        get: operations["read_model_availability_api_catalogue_models__slug__availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AllocatedAssetResponse
         * @description One physical unit held by the booking.
         */
        AllocatedAssetResponse: {
            /**
             * Allocationid
             * Format: uuid
             */
            allocationId: string;
            /**
             * Assetid
             * Format: uuid
             */
            assetId: string;
            /** Assettag */
            assetTag: string;
        };
        /**
         * AllocationRequest
         * @description A booking request posted by the client.
         *
         *     The period is half open. `endDate` is the day the unit comes back and is
         *     not charged, which is the same rule the exclusion constraint enforces.
         */
        AllocationRequest: {
            /**
             * Productmodelid
             * Format: uuid
             */
            productModelId: string;
            /**
             * Branchid
             * Format: uuid
             */
            branchId: string;
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /**
             * Enddate
             * Format: date
             */
            endDate: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Customeruserid */
            customerUserId?: string | null;
        };
        /**
         * AllocationResponse
         * @description The committed booking returned to the client.
         */
        AllocationResponse: {
            /**
             * Reservationid
             * Format: uuid
             */
            reservationId: string;
            /** Reference */
            reference: string;
            /**
             * Reservationlineid
             * Format: uuid
             */
            reservationLineId: string;
            /** Status */
            status: string;
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /**
             * Enddate
             * Format: date
             */
            endDate: string;
            /** Allocated */
            allocated: components["schemas"]["AllocatedAssetResponse"][];
        };
        /**
         * AvailabilityPageResponse
         * @description One page of an availability search.
         *
         *     `to` is the day the equipment comes back. It is exclusive, so a unit is
         *     free again on that day.
         */
        AvailabilityPageResponse: {
            /**
             * From
             * Format: date
             */
            from: string;
            /**
             * To
             * Format: date
             */
            to: string;
            /** Hiredays */
            hireDays: number;
            /** Items */
            items: components["schemas"]["ModelAvailabilityRowResponse"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /**
         * BranchAvailabilityResponse
         * @description Whether one branch can supply a model for the whole period asked about.
         */
        BranchAvailabilityResponse: {
            /** Branchcode */
            branchCode: string;
            /** Branchname */
            branchName: string;
            /** Available */
            available: boolean;
        };
        /**
         * BranchListResponse
         * @description The active branches, ordered by name.
         */
        BranchListResponse: {
            /** Items */
            items: components["schemas"]["BranchResponse"][];
        };
        /**
         * BranchResponse
         * @description One trading branch.
         */
        BranchResponse: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Suburb */
            suburb: string;
            /** City */
            city: string;
            /** Phone */
            phone: string;
            /** Opensat */
            opensAt: string;
            /** Closesat */
            closesAt: string;
        };
        /**
         * CategoryListResponse
         * @description The active categories, each parent followed by its children.
         */
        CategoryListResponse: {
            /** Items */
            items: components["schemas"]["CategoryResponse"][];
        };
        /**
         * CategoryResponse
         * @description One active category. `parentCode` is null for a top level category.
         */
        CategoryResponse: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description: string;
            /** Parentcode */
            parentCode: string | null;
            /** Sortorder */
            sortOrder: number;
            /** Modelcount */
            modelCount: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description What the health endpoint reports about its own dependencies.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Environment */
            environment: string;
            /** Databasereachable */
            databaseReachable: boolean;
            /** Btreegistinstalled */
            btreeGistInstalled: boolean;
            /** Revision */
            revision: string;
        };
        /**
         * ModelAvailabilityResponse
         * @description Where one model is free for a period, in the quantity asked for.
         */
        ModelAvailabilityResponse: {
            /**
             * From
             * Format: date
             */
            from: string;
            /**
             * To
             * Format: date
             */
            to: string;
            /** Hiredays */
            hireDays: number;
            /** Quantity */
            quantity: number;
            /** Branches */
            branches: components["schemas"]["BranchAvailabilityResponse"][];
        };
        /**
         * ModelAvailabilityRowResponse
         * @description One model of an availability search, with an answer from every branch.
         */
        ModelAvailabilityRowResponse: {
            model: components["schemas"]["ModelSummaryResponse"];
            /** Branches */
            branches: components["schemas"]["BranchAvailabilityResponse"][];
        };
        /**
         * ModelDetailResponse
         * @description A published catalogue entry as its own page shows it.
         */
        ModelDetailResponse: {
            /** Sku */
            sku: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Manufacturer */
            manufacturer: string;
            /** Modelnumber */
            modelNumber: string;
            /** Categorycode */
            categoryCode: string;
            /** Categoryname */
            categoryName: string;
            /** Shortdescription */
            shortDescription: string;
            /** Dailyrate */
            dailyRate: string;
            /** Weeklyrate */
            weeklyRate: string;
            /** Depositamount */
            depositAmount: string;
            /** Minhiredays */
            minHireDays: number;
            /** Maxhiredays */
            maxHireDays: number;
            /** Imagepath */
            imagePath: string | null;
            /** Longdescription */
            longDescription: string | null;
            /** Latefeeperday */
            lateFeePerDay: string;
        };
        /**
         * ModelPageResponse
         * @description One page of published models.
         */
        ModelPageResponse: {
            /** Items */
            items: components["schemas"]["ModelSummaryResponse"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /**
         * ModelSortParameter
         * @description The sort orders a request may name.
         * @enum {string}
         */
        ModelSortParameter: "name" | "dailyRateAsc" | "dailyRateDesc";
        /**
         * ModelSummaryResponse
         * @description A published catalogue entry as it appears in a list.
         */
        ModelSummaryResponse: {
            /** Sku */
            sku: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Manufacturer */
            manufacturer: string;
            /** Modelnumber */
            modelNumber: string;
            /** Categorycode */
            categoryCode: string;
            /** Categoryname */
            categoryName: string;
            /** Shortdescription */
            shortDescription: string;
            /** Dailyrate */
            dailyRate: string;
            /** Weeklyrate */
            weeklyRate: string;
            /** Depositamount */
            depositAmount: string;
            /** Minhiredays */
            minHireDays: number;
            /** Maxhiredays */
            maxHireDays: number;
            /** Imagepath */
            imagePath: string | null;
        };
        /**
         * ProblemDetail
         * @description An RFC 9457 problem document.
         *
         *     `type` is a stable slug, not a resolvable URL, because this API is not a
         *     public specification and inventing a documentation URL that does not exist
         *     is worse than a slug that does.
         *
         *     `requestId` is an extension member. It is the same value as the
         *     `X-Request-ID` response header and the `request_id` on every log record of
         *     the request, so a caller who quotes it has named the exact log lines.
         */
        ProblemDetail: {
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Instance */
            instance?: string | null;
            /** Errors */
            errors?: Record<string, unknown> | null;
            /** Requestid */
            requestId?: string | null;
        };
        /**
         * SignInRequest
         * @description Credentials posted to the sign in endpoint.
         *
         *     The address is checked structurally rather than with a full RFC 5322
         *     parser. Deliverability is proved by the verification email, not by a
         *     regular expression, so a validation library here would be a dependency
         *     that buys nothing.
         *
         *     The password carries no minimum length. It deliberately did once, and that
         *     was a defect: a wrong password of eleven characters came back as a 422
         *     naming the length rule, while a wrong password of twelve came back as a 401.
         *     That difference is an oracle. It tells an attacker something about the value
         *     they submitted, and it contradicts control C-14 in the security section,
         *     which states that an unknown address and a wrong password are answered
         *     identically in body, status and timing. Length policy applies when a
         *     password is chosen, not when one is presented, so it lives in
         *     `security.hash_password` (BR-45) and not here. The maximum stays, because it
         *     is a property of bcrypt rather than a rule about the account, and it applies
         *     to the unknown address and the wrong password alike.
         */
        SignInRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * TokenResponse
         * @description The access token and the account it belongs to.
         */
        TokenResponse: {
            /** Accesstoken */
            accessToken: string;
            /**
             * Tokentype
             * @default bearer
             */
            tokenType: string;
            /** Expiresin */
            expiresIn: number;
            user: components["schemas"]["UserResponse"];
        };
        /**
         * UserResponse
         * @description The signed in account, shaped like the frontend UserAccount type.
         */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Branchcode */
            branchCode?: string | null;
            /** Active */
            active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, unknown>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    post_sign_in_api_auth_sign_in_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    post_allocation_api_allocations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllocationResponse"];
                };
            };
            /** @description No free unit exists for the requested period. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_branches_api_branches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchListResponse"];
                };
            };
        };
    };
    list_categories_api_catalogue_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponse"];
                };
            };
        };
    };
    list_models_api_catalogue_models_get: {
        parameters: {
            query?: {
                /** @description A category slug. A parent category includes its children. */
                category?: string | null;
                /** @description Free text matched against name, manufacturer and model number. */
                q?: string | null;
                /** @description The order of the list. */
                sort?: components["schemas"]["ModelSortParameter"];
                /** @description The page, counted from 1. */
                page?: number;
                /** @description How many models a page holds. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPageResponse"];
                };
            };
            /** @description A query parameter was refused. `errors.fields` names it. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    read_model_api_catalogue_models__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDetailResponse"];
                };
            };
            /** @description No published model carries this slug. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_availability_api_catalogue_availability_get: {
        parameters: {
            query: {
                /** @description The first day of the hire. */
                from: string;
                /** @description The day the equipment comes back. It is free again that day. */
                to: string;
                /** @description A branch code. Only models free at this branch are listed. */
                branch?: string | null;
                /** @description A category slug. A parent category includes its children. */
                category?: string | null;
                /** @description Free text matched against name, manufacturer and model number. */
                q?: string | null;
                /** @description The order of the list. */
                sort?: components["schemas"]["ModelSortParameter"];
                /** @description The page, counted from 1. */
                page?: number;
                /** @description How many models a page holds. */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityPageResponse"];
                };
            };
            /** @description A query parameter was refused. `errors.fields` names it. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    read_model_availability_api_catalogue_models__slug__availability_get: {
        parameters: {
            query: {
                /** @description The first day of the hire. */
                from: string;
                /** @description The day the equipment comes back. It is free again that day. */
                to: string;
                /** @description How many units are wanted at one branch. */
                quantity?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelAvailabilityResponse"];
                };
            };
            /** @description No published model carries this slug. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description A query parameter was refused. `errors.fields` names it. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
