"""Booking and allocation: Reservation, ReservationLine and AssetAllocation.

AssetAllocation stores plain `start_date` and `end_date` date columns. The
`daterange` is built inside the exclusion constraint expression rather than
being exposed as a range column, so ordinary queries and reports read normal
date columns and SQLModel stays simple.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from uuid import UUID, uuid4

from sqlalchemy import (
    Column,
    Computed,
    Date,
    ForeignKeyConstraint,
    Integer,
    SmallInteger,
    Text,
    UniqueConstraint,
)
from sqlmodel import Field, SQLModel

from app.domain.enums import (
    RELEASE_REASON_TYPE,
    RESERVATION_STATUS_TYPE,
    ReleaseReason,
    ReservationStatus,
)
from app.infrastructure.models.columns import (
    ON_DELETE,
    created_at_column,
    enum_column,
    money,
    percent,
    timestamp,
    updated_at_column,
    uuid_column,
    uuid_fk,
    uuid_pk,
    varchar,
)

REFERENCE_MAX_LENGTH = 16
NO_DISCOUNT = Decimal("0")


class Reservation(SQLModel, table=True):
    """A customer booking of one or more product models at one branch.

    `customer_profile_id` points at the profile and not at the account, so a
    walk-in with no login can still own a booking history. `created_by_user_id`
    is kept separate, so a counter booking names both the customer and the
    assistant who raised it.

    `hire_days` is generated by the database from the two dates. It is never
    written, and it reads as None until the row has been flushed.
    """

    __tablename__ = "reservation"

    id: UUID = Field(default_factory=uuid4, sa_column=uuid_pk())
    reference: str = Field(sa_column=varchar(REFERENCE_MAX_LENGTH, unique=True))
    customer_profile_id: UUID = Field(sa_column=uuid_fk("customer_profile.id"))
    branch_id: UUID = Field(sa_column=uuid_fk("branch.id"))
    start_date: date = Field(sa_column=Column(Date, nullable=False))
    # Exclusive. The day the unit comes back.
    end_date: date = Field(sa_column=Column(Date, nullable=False))
    status: ReservationStatus = Field(
        sa_column=enum_column(ReservationStatus, RESERVATION_STATUS_TYPE)
    )
    hire_days: int | None = Field(
        default=None,
        sa_column=Column(
            Integer, Computed("end_date - start_date", persisted=True), nullable=False
        ),
    )
    # The four totals are a snapshot taken when the booking is created.
    subtotal_ex_vat: Decimal = Field(sa_column=money())
    vat_amount: Decimal = Field(sa_column=money())
    deposit_total: Decimal = Field(sa_column=money())
    estimated_total_inc_vat: Decimal = Field(sa_column=money())
    # Set while the status is HELD (BR-12).
    hold_expires_at: datetime | None = Field(default=None, sa_column=timestamp())
    created_by_user_id: UUID = Field(sa_column=uuid_fk("user_account.id"))
    confirmed_at: datetime | None = Field(default=None, sa_column=timestamp())
    cancelled_at: datetime | None = Field(default=None, sa_column=timestamp())
    cancellation_reason: str | None = Field(default=None, sa_column=varchar(200, nullable=True))
    notes: str | None = Field(default=None, sa_column=Column(Text, nullable=True))
    created_at: datetime | None = Field(default=None, sa_column=created_at_column())
    updated_at: datetime | None = Field(default=None, sa_column=updated_at_column())


class ReservationLine(SQLModel, table=True):
    """One product model and a quantity within a reservation, with price snapshots.

    The snapshot columns are copied from the product model when the line is
    created, so a later price change never rewrites an existing booking (BR-20).
    """

    __tablename__ = "reservation_line"
    __table_args__ = (
        UniqueConstraint(
            "reservation_id", "product_model_id", name="uq_reservation_line_model_once"
        ),
    )

    id: UUID = Field(default_factory=uuid4, sa_column=uuid_pk())
    reservation_id: UUID = Field(sa_column=uuid_fk("reservation.id"))
    product_model_id: UUID = Field(sa_column=uuid_fk("product_model.id"))
    quantity: int = Field(sa_column=Column(SmallInteger, nullable=False))
    line_position: int = Field(sa_column=Column(SmallInteger, nullable=False))
    daily_rate_snapshot: Decimal = Field(sa_column=money())
    weekly_rate_snapshot: Decimal = Field(sa_column=money())
    deposit_snapshot: Decimal = Field(sa_column=money())
    late_fee_per_day_snapshot: Decimal = Field(sa_column=money())
    replacement_value_snapshot: Decimal = Field(sa_column=money())
    # The trade discount at the time of booking.
    discount_percent: Decimal = Field(default=NO_DISCOUNT, sa_column=percent(default="0"))
    # The output of the pricing policy (BR-21).
    line_subtotal_ex_vat: Decimal = Field(sa_column=money())
    created_at: datetime | None = Field(default=None, sa_column=created_at_column())
    updated_at: datetime | None = Field(default=None, sa_column=updated_at_column())


class AssetAllocation(SQLModel, table=True):
    """The reservation of one specific asset for one specific half open period.

    This is the table that makes double booking impossible. The exclusion
    constraint `asset_allocation_no_overlap` is created by raw DDL in the
    migration, because Alembic autogenerate will not invent one.

    An allocation is active exactly while `released_at` is null. The reason and
    the timestamp arrive together, which the release state check enforces, so
    there is no status column to disagree with them.
    """

    __tablename__ = "asset_allocation"
    __table_args__ = (
        ForeignKeyConstraint(
            ["asset_id", "branch_id"],
            ["asset.id", "asset.branch_id"],
            name="fk_asset_allocation_asset_branch",
            ondelete=ON_DELETE,
        ),
        UniqueConstraint("id", "asset_id", name="uq_asset_allocation_id_asset"),
    )

    id: UUID = Field(default_factory=uuid4, sa_column=uuid_pk())
    reservation_line_id: UUID = Field(sa_column=uuid_fk("reservation_line.id"))
    asset_id: UUID = Field(sa_column=uuid_column())
    branch_id: UUID = Field(sa_column=uuid_column())
    start_date: date = Field(sa_column=Column(Date, nullable=False))
    end_date: date = Field(sa_column=Column(Date, nullable=False))
    allocated_at: datetime | None = Field(
        default=None, sa_column=timestamp(nullable=False, default_now=True)
    )
    released_at: datetime | None = Field(default=None, sa_column=timestamp())
    release_reason: ReleaseReason | None = Field(
        default=None, sa_column=enum_column(ReleaseReason, RELEASE_REASON_TYPE, nullable=True)
    )
    created_at: datetime | None = Field(default=None, sa_column=created_at_column())
    updated_at: datetime | None = Field(default=None, sa_column=updated_at_column())
