"""Initial schema: extensions, enum types, core tables and the overlap constraint.

Hand written rather than autogenerated. Alembic cannot invent an exclusion
constraint, so the one piece of DDL the whole design depends on would be
missing from a generated migration. The rest is written alongside it so the
schema is readable in one place.

The constraint text, the enum members and the extension list live in
app.infrastructure.schema_ddl, so the migration, the allocation use case and the
tests all read one definition instead of three copies.

Revision ID: 0001
Revises:
Created: 2026-08-15
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.infrastructure.schema_ddl import (
    BRANCH_SCOPE_CHECK_DDL,
    ENUM_TYPES,
    EXCLUSION_CONSTRAINT_DDL,
    REFERENCE_SEQUENCE,
    REFERENCE_SEQUENCE_START,
    RELEASE_STATE_CHECK_DDL,
    REQUIRED_EXTENSIONS,
)

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def _uuid_pk() -> sa.Column[sa.Uuid]:
    """Return the standard application generated UUID primary key column."""
    return sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False)


def _enum(type_name: str, column_name: str = "status") -> sa.Column[str]:
    """Return a NOT NULL column bound to an enum type this migration created."""
    return sa.Column(
        column_name,
        postgresql.ENUM(*ENUM_TYPES[type_name], name=type_name, create_type=False),
        nullable=False,
    )


def _money(name: str) -> sa.Column[sa.Numeric]:
    """Return a NUMERIC(12,2) column. Money is never floating point."""
    return sa.Column(name, sa.Numeric(12, 2), nullable=False)


def _timestamps(*, with_updated: bool = True) -> list[sa.Column[sa.DateTime]]:
    """Return the standard created_at and updated_at columns."""
    columns = [
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        )
    ]
    if with_updated:
        columns.append(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text("now()"),
            )
        )
    return columns


def _fk(name: str, target: str, *, nullable: bool = False) -> sa.Column[sa.Uuid]:
    """Return a UUID foreign key column. Nothing is ever hard deleted (BR-51)."""
    return sa.Column(
        name,
        postgresql.UUID(as_uuid=True),
        sa.ForeignKey(target, ondelete="RESTRICT"),
        nullable=nullable,
    )


def upgrade() -> None:
    """Create the extensions, enum types, tables, sequence and constraints."""
    for extension in REQUIRED_EXTENSIONS:
        op.execute(f"CREATE EXTENSION IF NOT EXISTS {extension}")

    bind = op.get_bind()
    for type_name, values in ENUM_TYPES.items():
        postgresql.ENUM(*values, name=type_name).create(bind, checkfirst=True)

    op.create_table(
        "branches",
        _uuid_pk(),
        sa.Column("code", sa.String(4), nullable=False, unique=True),
        sa.Column("name", sa.String(80), nullable=False),
        sa.Column("suburb", sa.String(80), nullable=False),
        sa.Column("city", sa.String(80), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        *_timestamps(),
    )

    op.create_table(
        "user_accounts",
        _uuid_pk(),
        sa.Column("email", postgresql.CITEXT(), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(120), nullable=False),
        _enum("user_role", "role"),
        sa.Column("full_name", sa.String(120), nullable=False),
        sa.Column("phone", sa.String(20), nullable=True),
        _fk("branch_id", "branches.id", nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
    )
    op.execute(BRANCH_SCOPE_CHECK_DDL)

    op.create_table(
        "product_models",
        _uuid_pk(),
        sa.Column("sku", sa.String(24), nullable=False, unique=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("slug", sa.String(140), nullable=False, unique=True),
        sa.Column("manufacturer", sa.String(80), nullable=False),
        sa.Column("short_description", sa.String(300), nullable=False),
        _money("daily_rate"),
        _money("deposit_amount"),
        _money("late_fee_per_day"),
        _money("replacement_value"),
        sa.Column("is_published", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        *_timestamps(),
    )

    op.create_table(
        "assets",
        _uuid_pk(),
        sa.Column("asset_tag", sa.String(16), nullable=False, unique=True),
        _fk("product_model_id", "product_models.id"),
        _fk("branch_id", "branches.id"),
        sa.Column("serial_number", sa.String(60), nullable=True),
        _enum("asset_status"),
        _enum("condition_grade", "condition_grade"),
        sa.Column("acquired_on", sa.Date(), nullable=False),
        _money("acquisition_cost"),
        sa.Column("hour_meter_reading", sa.Integer(), nullable=True),
        *_timestamps(),
        # Exists so asset_allocations can carry a composite foreign key and the
        # database itself refuses an allocation that puts a unit at the wrong
        # branch. Phase one has no inter branch transfer (BR-06).
        sa.UniqueConstraint("id", "branch_id", name="uq_assets_id_branch"),
    )
    op.create_index("ix_assets_model_branch", "assets", ["product_model_id", "branch_id"])

    op.create_table(
        "reservations",
        _uuid_pk(),
        sa.Column("reference", sa.String(16), nullable=False, unique=True),
        _fk("customer_user_id", "user_accounts.id"),
        _fk("branch_id", "branches.id"),
        _enum("reservation_status"),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        _fk("created_by_user_id", "user_accounts.id"),
        sa.Column("notes", sa.String(300), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("end_date > start_date", name="ck_reservations_period"),
        sa.CheckConstraint("end_date - start_date <= 28", name="ck_reservations_max_hire_days"),
    )

    op.create_table(
        "reservation_lines",
        _uuid_pk(),
        _fk("reservation_id", "reservations.id"),
        _fk("product_model_id", "product_models.id"),
        sa.Column("quantity", sa.SmallInteger(), nullable=False),
        sa.Column("line_position", sa.SmallInteger(), nullable=False),
        _money("daily_rate_snapshot"),
        _money("deposit_snapshot"),
        *_timestamps(with_updated=False),
        sa.CheckConstraint(
            "quantity >= 1 AND quantity <= 10", name="ck_reservation_lines_quantity"
        ),
        sa.UniqueConstraint(
            "reservation_id", "product_model_id", name="uq_reservation_lines_model_once"
        ),
    )

    op.create_table(
        "asset_allocations",
        _uuid_pk(),
        _fk("reservation_line_id", "reservation_lines.id"),
        sa.Column("asset_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("branch_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        _enum("allocation_status"),
        sa.Column(
            "allocated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id", "branch_id"],
            ["assets.id", "assets.branch_id"],
            name="fk_asset_allocations_asset_branch",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint("id", "asset_id", name="uq_asset_allocations_id_asset"),
        sa.CheckConstraint("end_date > start_date", name="ck_asset_allocations_period"),
    )
    op.execute(RELEASE_STATE_CHECK_DDL)
    op.execute(EXCLUSION_CONSTRAINT_DDL)
    op.create_index(
        "ix_asset_allocations_line",
        "asset_allocations",
        ["reservation_line_id"],
    )

    op.execute(f"CREATE SEQUENCE {REFERENCE_SEQUENCE} START {REFERENCE_SEQUENCE_START}")


def downgrade() -> None:
    """Drop the tables, the sequence and the enum types, in dependency order.

    The extensions are left installed. They are database wide and may be in use
    by something else, so removing them would reach outside this migration.
    """
    op.execute(f"DROP SEQUENCE IF EXISTS {REFERENCE_SEQUENCE}")
    for table in (
        "asset_allocations",
        "reservation_lines",
        "reservations",
        "assets",
        "product_models",
        "user_accounts",
        "branches",
    ):
        op.drop_table(table)
    bind = op.get_bind()
    for type_name in reversed(list(ENUM_TYPES)):
        postgresql.ENUM(name=type_name).drop(bind, checkfirst=True)
