"""Initial schema: the documented baseline of seventeen tables.

Hand written rather than autogenerated. Alembic will not write an extension, an
exclusion constraint or a partial index, so the pieces the whole design depends
on would be missing from a generated migration.

This file is only the orchestrator. Seventeen tables with their constraints and
indexes do not fit in one readable file, so the definitions live in the
`baseline` package beside the `versions` directory, one module per subject
area. That package is a frozen snapshot and imports nothing from the
application.

The order below is the dependency order. The extensions and the enumerated
types come first, then identity, the catalogue, booking, hire and the
supporting tables. The downgrade walks the same list backwards and drops
everything the upgrade created.

Revision ID: 0001
Revises:
Created: 2026-08-15
"""

from __future__ import annotations

import sys
from collections.abc import Sequence
from pathlib import Path

# The baseline package sits in the alembic directory, which is not a package
# and is not on the import path. Alembic loads this file by its path, so a
# relative import is not available either. The directory is added here, from
# this file's own location, so the import works for every alembic command and
# from any working directory.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from baseline import booking, catalogue, evidence, hire, identity, prerequisites

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Parents before children. Each module exposes create() and drop().
SUBJECT_AREAS = (identity, catalogue, booking, hire, evidence)


def upgrade() -> None:
    """Create the extensions, the enumerated types and all seventeen tables."""
    prerequisites.create()
    for area in SUBJECT_AREAS:
        area.create()


def downgrade() -> None:
    """Drop everything the upgrade created, children before parents."""
    for area in reversed(SUBJECT_AREAS):
        area.drop()
    prerequisites.drop()
